### ISSUE TITLE
Always returns false

### ISSUE THREAD

**Issue by XaphanBael** [Centillien/check_email#1]
Tried it today, but all domains return false, including gmail.com, hotmail.com

**Comment by gerard-kanters** [comment]
Do you have a working internet connection from your server ? If you check an existing gmail account, it will return true.

**Comment by XaphanBael** [comment]
Sorry for the late response, but here's what i found.

1) My server had a firewall blockade on the sockets, after fixing this, it worked.
2) gmail and hotmail always return false.

So yes, it seems to work, but some hosts seem to block it.
